---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2024/7/15 20:48
---

if (redis.call("get", KEYS[1]) == ARGV[1]) then
    return redis.call("del", KEYS[1])
end
return 0